# Remove build artifacts
@clean:
    echo "{{BLUE}}Removing async build artifacts...{{NORMAL}}"
    cargo clean

# Format and lint
@check:
    echo "{{BLUE}}Formatting and linting async...{{NORMAL}}"
    cargo +nightly fmt --all
    cargo +nightly clippy --workspace --all-features -- -D warnings

# Sort dependencies
@sort:
    echo "{{BLUE}}Sorting async dependencies...{{NORMAL}}"
    cargo sort -g

# Update dependencies
@update:
    echo "{{BLUE}}Updating async dependencies...{{NORMAL}}"
    cargo update

# Check for outdated  dependencies
@outdated:
    echo "{{BLUE}}Checking for outdated async dependencies...{{NORMAL}}"
    cargo outdated -R

# Debug build
@debug:
    echo "{{BLUE}}Building async in debug mode...{{NORMAL}}"
    cargo build

# Release  build
@release:
    echo "{{BLUE}}Building async in release mode...{{NORMAL}}"
    cargo build --release