# Remove build artifacts
@clean:
    echo "{{BLUE}}Removing board build artifacts...{{NORMAL}}"
    cargo clean

# Format and lint
@check:
    echo "{{BLUE}}Formatting and linting board...{{NORMAL}}"
    cargo +nightly fmt --all
    cargo +nightly clippy --workspace --all-features -- -D warnings

# Sort dependencies
@sort:
    echo "{{BLUE}}Sorting board dependencies...{{NORMAL}}"
    cargo sort -g

# Update dependencies
@update:
    echo "{{BLUE}}Updating board dependencies...{{NORMAL}}"
    cargo update

# Check for outdated  dependencies
@outdated:
    echo "{{BLUE}}Checking for outdated board dependencies...{{NORMAL}}"
    cargo outdated -R

# Debug build
@debug:
    echo "{{BLUE}}Building board in debug mode...{{NORMAL}}"
    cargo build

# Release  build
@release:
    echo "{{BLUE}}Building board in release mode...{{NORMAL}}"
    cargo build --release